/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.sportsflash;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int baseballtexture2=0x7f020000;
        public static final int bballtexture2=0x7f020001;
        public static final int footballtexture2=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int solid_blue=0x7f020006;
        public static final int solid_green=0x7f020007;
        public static final int solid_red=0x7f020005;
        public static final int swing=0x7f020004;
    }
    public static final class id {
        public static final int empty=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int mlbplayer_list=0x7f030001;
        public static final int team_management=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int menu_team_management=0x7f040002;
        public static final int menu_view_league=0x7f040004;
        public static final int menu_view_players=0x7f040003;
        public static final int menu_view_team=0x7f040005;
        public static final int no_players=0x7f040001;
    }
    public static final class style {
        public static final int edit_text=0x7f050002;
        public static final int intro_blurb=0x7f050000;
        public static final int label=0x7f050001;
        /**   this is the style for the container ListView, not the rows 
         */
        public static final int review_list=0x7f050006;
        public static final int spinner_item=0x7f050004;
        public static final int spinner_item_dropdown=0x7f050005;
        public static final int view_text=0x7f050003;
    }
}
